package navidrome
package navidrome

import (
	"bytes"




















































































































































































































































}	return ""	}		}			}				return s			if s, ok := raw.(string); ok {		if raw, ok := m[k]; ok {	for _, k := range keys {	keys := []string{"token", "idToken", "jwt", "accessToken"}func pickToken(m map[string]any) string {}	return nil	}		return err		}			return nil		if errors.Is(err, io.EOF) {	if err := json.NewDecoder(resp.Body).Decode(out); err != nil {	}		return nil	if out == nil {	}		return fmt.Errorf("navidrome api %s %s failed: %d: %s", method, endpoint, resp.StatusCode, strings.TrimSpace(string(b)))		b, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return err	if err != nil {	resp, err := c.httpClient.Do(req)	}		req.Header.Set("Authorization", "Bearer "+token)	if token != "" {	c.mu.RUnlock()	token := c.token	c.mu.RLock()	req.Header.Set("Content-Type", "application/json")	}		return err	if err != nil {	req, err := http.NewRequestWithContext(ctx, method, c.baseURL+endpoint, body)	}		body = bytes.NewReader(b)		}			return err		if err != nil {		b, err := json.Marshal(payload)	if payload != nil {	var body io.Readerfunc (c *HTTPClient) doJSON(ctx context.Context, method, endpoint string, payload any, out any) error {}	return resp.Items, nil	}		return nil, err	if err := c.doJSON(ctx, http.MethodGet, "/api/playlist", nil, &resp); err != nil {	}		Items []playlistInfo `json:"items"`	var resp struct {func (c *HTTPClient) listPlaylists(ctx context.Context) ([]playlistInfo, error) {}	Name string `json:"name"`	ID   string `json:"id"`type playlistInfo struct {}	return c.doJSON(ctx, http.MethodDelete, endpoint, nil, nil)	endpoint := fmt.Sprintf("/api/playlist/%s/tracks/%s", url.PathEscape(playlistID), url.PathEscape(trackID))func (c *HTTPClient) RemoveTrack(ctx context.Context, playlistID, trackID string) error {}	return c.doJSON(ctx, http.MethodPost, endpoint, payload, nil)	endpoint := fmt.Sprintf("/api/playlist/%s/tracks", url.PathEscape(playlistID))	}		"position": position,		"trackID":  trackID,	payload := map[string]any{func (c *HTTPClient) AddOrMoveTrack(ctx context.Context, playlistID, trackID string, position int) error {}	return resp.Items[0].ID, nil	}		return "", errors.New("track not found in navidrome")	if len(resp.Items) == 0 || resp.Items[0].ID == "" {	}		return "", err	if err := c.doJSON(ctx, http.MethodGet, endpoint, nil, &resp); err != nil {	}		} `json:"items"`			ID string `json:"id"`		Items []struct {	var resp struct {	}		endpoint += "?" + encoded	if encoded := query.Encode(); encoded != "" {	endpoint := "/api/song"	}		query.Set("title", selector.Title)	if selector.Title != "" {	}		query.Set("artist", selector.Artist)	if selector.Artist != "" {	}		query.Set("path", selector.FilePath)	if selector.FilePath != "" {	query := url.Values{}	}		return selector.TrackID, nil	if selector.TrackID != "" {func (c *HTTPClient) ResolveTrack(ctx context.Context, selector TrackSelector) (string, error) {}	return c.doJSON(ctx, http.MethodDelete, "/api/playlist/"+url.PathEscape(playlistID), nil, nil)func (c *HTTPClient) DeletePlaylist(ctx context.Context, playlistID string) error {}	return created.ID, nil	}		return "", errors.New("navidrome create playlist returned empty id")	if created.ID == "" {	}		return "", err	if err := c.doJSON(ctx, http.MethodPost, "/api/playlist", map[string]any{"name": name}, &created); err != nil {	}		ID string `json:"id"`	var created struct {	}		}			return p.ID, nil		if strings.EqualFold(p.Name, name) {	for _, p := range playlists {	}		return "", err	if err != nil {	playlists, err := c.listPlaylists(ctx)func (c *HTTPClient) EnsurePlaylist(ctx context.Context, name string) (string, error) {}	return nil	c.mu.Unlock()	c.token = token	c.mu.Lock()	}		return errors.New("navidrome login response does not contain token")	if token == "" {	token := pickToken(result)	}		return fmt.Errorf("decode login response: %w", err)	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {	var result map[string]any	}		return fmt.Errorf("navidrome login failed: status %d: %s", resp.StatusCode, strings.TrimSpace(string(b)))		b, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))	if resp.StatusCode >= 300 {	defer resp.Body.Close()	}		return err	if err != nil {	resp, err := c.httpClient.Do(req)	req.Header.Set("Content-Type", "application/json")	}		return err	if err != nil {	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.baseURL+"/auth/login", bytes.NewReader(body))	body, _ := json.Marshal(payload)	payload := map[string]string{"username": username, "password": password}func (c *HTTPClient) Login(ctx context.Context, username, password string) error {}	}		},			Timeout: 15 * time.Second,		httpClient: &http.Client{		baseURL: strings.TrimRight(baseURL, "/"),	return &HTTPClient{func NewHTTPClient(baseURL string) *HTTPClient {}	token string	mu    sync.RWMutex	httpClient *http.Client	baseURL    stringtype HTTPClient struct {}	return NewHTTPClient(baseURL)func (f *HTTPClientFactory) New(baseURL string) Client {}	return &HTTPClientFactory{}func NewHTTPClientFactory() *HTTPClientFactory {type HTTPClientFactory struct{}}	New(baseURL string) Clienttype ClientFactory interface {}	RemoveTrack(ctx context.Context, playlistID, trackID string) error	AddOrMoveTrack(ctx context.Context, playlistID, trackID string, position int) error	ResolveTrack(ctx context.Context, selector TrackSelector) (string, error)	DeletePlaylist(ctx context.Context, playlistID string) error	EnsurePlaylist(ctx context.Context, name string) (string, error)	Login(ctx context.Context, username, password string) errortype Client interface {}	Title    string	Artist   string	FilePath string	TrackID  stringtype TrackSelector struct {)	"time"	"sync"	"strings"	"net/url"	"net/http"	"io"	"fmt"	"errors"	"encoding/json"	"context"