image:
  repository: ghcr.io/m1xxos/navidrome-k8s-operator
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

leaderElection: false
serviceAccount:
  create: true
  name: ""
